/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expense.manager;

import static expense.manager.SignIn.getCon;
import expense.manager.HintTextField;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author chaudhari ji
 */
public class ExpenseEntry extends javax.swing.JFrame {
    int userid;
    WelcomePage p;
    /**
     * Creates new form ExpenseEntry
     */
    public ExpenseEntry(int uid,WelcomePage p) {
        initComponents();
        this.userid=uid;
        this.p=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rupees_label = new javax.swing.JLabel();
        expenseField =new javax.swing.JTextField();
        type_choice = new java.awt.Choice();
        submitButton = new javax.swing.JButton();
        NoteTextField =  new HintTextField("Add a note");
	
	type_choice.add("Food");
	type_choice.add("Tranportation");
	type_choice.add("Health");
	type_choice.add("Shopping");
	type_choice.add("Utilities");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rupees_label.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rupees_label.setText(" ₹");

        expenseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseFieldActionPerformed(evt);
            }
        });
        expenseField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expenseFieldKeyTyped(evt);
            }
        });

        submitButton.setText("✔ Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(type_choice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rupees_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expenseField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expenseField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rupees_label))
                .addGap(2, 2, 2)
                .addComponent(type_choice, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expenseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_expenseFieldActionPerformed

    private void expenseFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expenseFieldKeyTyped
        char c=evt.getKeyChar();
        if(!(Character .isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_expenseFieldKeyTyped

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try{
            Connection con=getCon("root","root");
            if(con!=null)
                System.out.println("Connection Successfull!");
            else
                System.out.println("Connection Unsuccessfull!");
            PreparedStatement ps=con.prepareStatement("INSERT INTO `expensemanager`.`universalpassbook` (uid,dateNtime,expense_type,credited,expense_debited,note) VALUES(?,NOW(),?,null,?,?);"); 
            ps.setInt(1, this.userid );
            System.out.println(this.userid);
            ps.setString(2, type_choice.getSelectedItem());
            System.out.println(type_choice.getSelectedItem());
            String expense=expenseField.getText();
            float exp=Float.parseFloat(expense);
            ps.setFloat(3, exp);
            System.out.println(exp);
            String note =NoteTextField.getText();
            System.out.println(note);
            ps.setString(4, note );
            ps.executeUpdate();
            ps.close();
            con.close();
            dispose();
            this.p.setVisible(true);
	}catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_submitButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpenseEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpenseEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpenseEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpenseEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ExpenseEntry(1).setVisible(true);
            }
        });*/
    }

    
//    -----------------------------------------------------------------------------------------------
//    -----------------------------------------------------------------------------------------------
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NoteTextField;
    private javax.swing.JTextField expenseField;
    private javax.swing.JLabel rupees_label;
    private javax.swing.JButton submitButton;
    private java.awt.Choice type_choice;
    // End of variables declaration//GEN-END:variables
}

